<?php

return array (
  'database' => 
  array (
    'default_character_set_name' => 'utf8mb4',
    'default_collation_name' => 'utf8mb4_general_ci',
  ),
  'tables' => 
  array (
    'note' => 
    array (
      'table' => 
      array (
        'table_name' => 'note',
        'engine' => 'InnoDB',
        'table_comment' => '',
        'table_collation' => 'utf8_general_ci',
        'character_set_name' => 'utf8',
        'row_format' => 'Dynamic',
      ),
      'columns' => 
      array (
        'id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'note',
          'COLUMN_NAME' => 'id',
          'ORDINAL_POSITION' => 1,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => 'auto_increment',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'user_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'note',
          'COLUMN_NAME' => 'user_id',
          'ORDINAL_POSITION' => 2,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => 'MUL',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'client_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'note',
          'COLUMN_NAME' => 'client_id',
          'ORDINAL_POSITION' => 3,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => 'MUL',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'message' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'note',
          'COLUMN_NAME' => 'message',
          'ORDINAL_POSITION' => 4,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 1000,
          'CHARACTER_OCTET_LENGTH' => 3000,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8',
          'COLLATION_NAME' => 'utf8_general_ci',
          'COLUMN_TYPE' => 'varchar(1000)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'is_main' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'note',
          'COLUMN_NAME' => 'is_main',
          'ORDINAL_POSITION' => 5,
          'COLUMN_DEFAULT' => '0',
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'tinyint',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 3,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'tinyint(1)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Bool if it\'s the client\'s main note',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'hidden' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'note',
          'COLUMN_NAME' => 'hidden',
          'ORDINAL_POSITION' => 6,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'tinyint',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 3,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'tinyint(4)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'updated_at' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'note',
          'COLUMN_NAME' => 'updated_at',
          'ORDINAL_POSITION' => 7,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'datetime',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => 0,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'datetime',
          'COLUMN_KEY' => '',
          'EXTRA' => 'on update current_timestamp()',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'created_at' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'note',
          'COLUMN_NAME' => 'created_at',
          'ORDINAL_POSITION' => 8,
          'COLUMN_DEFAULT' => 'current_timestamp()',
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'datetime',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => 0,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'datetime',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'deleted_at' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'note',
          'COLUMN_NAME' => 'deleted_at',
          'ORDINAL_POSITION' => 9,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'datetime',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => 0,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'datetime',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
      ),
      'indexes' => 
      array (
        'PRIMARY' => 
        array (
          1 => 
          array (
            'Table' => 'note',
            'Non_unique' => 0,
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => 1,
            'Column_name' => 'id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'FK__user' => 
        array (
          1 => 
          array (
            'Table' => 'note',
            'Non_unique' => 1,
            'Key_name' => 'FK__user',
            'Seq_in_index' => 1,
            'Column_name' => 'user_id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'FK_note_client' => 
        array (
          1 => 
          array (
            'Table' => 'note',
            'Non_unique' => 1,
            'Key_name' => 'FK_note_client',
            'Seq_in_index' => 1,
            'Column_name' => 'client_id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => NULL,
    ),
    'authentication_log' => 
    array (
      'table' => 
      array (
        'table_name' => 'authentication_log',
        'engine' => 'InnoDB',
        'table_comment' => '',
        'table_collation' => 'utf8mb4_general_ci',
        'character_set_name' => 'utf8mb4',
        'row_format' => 'Dynamic',
      ),
      'columns' => 
      array (
        'id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'authentication_log',
          'COLUMN_NAME' => 'id',
          'ORDINAL_POSITION' => 1,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => 'auto_increment',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'user_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'authentication_log',
          'COLUMN_NAME' => 'user_id',
          'ORDINAL_POSITION' => 2,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => 'MUL',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'email' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'authentication_log',
          'COLUMN_NAME' => 'email',
          'ORDINAL_POSITION' => 3,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 254,
          'CHARACTER_OCTET_LENGTH' => 1016,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_general_ci',
          'COLUMN_TYPE' => 'varchar(254)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'ip_address' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'authentication_log',
          'COLUMN_NAME' => 'ip_address',
          'ORDINAL_POSITION' => 4,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 45,
          'CHARACTER_OCTET_LENGTH' => 180,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_general_ci',
          'COLUMN_TYPE' => 'varchar(45)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'is_success' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'authentication_log',
          'COLUMN_NAME' => 'is_success',
          'ORDINAL_POSITION' => 5,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'tinyint',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 3,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'tinyint(4)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'created_at' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'authentication_log',
          'COLUMN_NAME' => 'created_at',
          'ORDINAL_POSITION' => 6,
          'COLUMN_DEFAULT' => 'current_timestamp()',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'datetime',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => 0,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'datetime',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
      ),
      'indexes' => 
      array (
        'PRIMARY' => 
        array (
          1 => 
          array (
            'Table' => 'authentication_log',
            'Non_unique' => 0,
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => 1,
            'Column_name' => 'id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'authentication_log_user_id_fk' => 
        array (
          1 => 
          array (
            'Table' => 'authentication_log',
            'Non_unique' => 1,
            'Key_name' => 'authentication_log_user_id_fk',
            'Seq_in_index' => 1,
            'Column_name' => 'user_id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => 'YES',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => NULL,
    ),
    'email_log' => 
    array (
      'table' => 
      array (
        'table_name' => 'email_log',
        'engine' => 'InnoDB',
        'table_comment' => '',
        'table_collation' => 'utf8mb4_general_ci',
        'character_set_name' => 'utf8mb4',
        'row_format' => 'Dynamic',
      ),
      'columns' => 
      array (
        'id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'email_log',
          'COLUMN_NAME' => 'id',
          'ORDINAL_POSITION' => 1,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => 'auto_increment',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'user_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'email_log',
          'COLUMN_NAME' => 'user_id',
          'ORDINAL_POSITION' => 2,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => 'MUL',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'from_email' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'email_log',
          'COLUMN_NAME' => 'from_email',
          'ORDINAL_POSITION' => 3,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 254,
          'CHARACTER_OCTET_LENGTH' => 1016,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_general_ci',
          'COLUMN_TYPE' => 'varchar(254)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'to_email' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'email_log',
          'COLUMN_NAME' => 'to_email',
          'ORDINAL_POSITION' => 4,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 254,
          'CHARACTER_OCTET_LENGTH' => 1016,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_general_ci',
          'COLUMN_TYPE' => 'varchar(254)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'other_recipient' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'email_log',
          'COLUMN_NAME' => 'other_recipient',
          'ORDINAL_POSITION' => 5,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 1000,
          'CHARACTER_OCTET_LENGTH' => 4000,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_general_ci',
          'COLUMN_TYPE' => 'varchar(1000)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'subject' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'email_log',
          'COLUMN_NAME' => 'subject',
          'ORDINAL_POSITION' => 6,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 998,
          'CHARACTER_OCTET_LENGTH' => 3992,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_general_ci',
          'COLUMN_TYPE' => 'varchar(998)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'created_at' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'email_log',
          'COLUMN_NAME' => 'created_at',
          'ORDINAL_POSITION' => 7,
          'COLUMN_DEFAULT' => 'current_timestamp()',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'datetime',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => 0,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'datetime',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
      ),
      'indexes' => 
      array (
        'PRIMARY' => 
        array (
          1 => 
          array (
            'Table' => 'email_log',
            'Non_unique' => 0,
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => 1,
            'Column_name' => 'id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'email_log_user_id_fk' => 
        array (
          1 => 
          array (
            'Table' => 'email_log',
            'Non_unique' => 1,
            'Key_name' => 'email_log_user_id_fk',
            'Seq_in_index' => 1,
            'Column_name' => 'user_id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => 'YES',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => NULL,
    ),
    'user_filter_setting' => 
    array (
      'table' => 
      array (
        'table_name' => 'user_filter_setting',
        'engine' => 'InnoDB',
        'table_comment' => '',
        'table_collation' => 'utf8mb4_general_ci',
        'character_set_name' => 'utf8mb4',
        'row_format' => 'Dynamic',
      ),
      'columns' => 
      array (
        'user_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'user_filter_setting',
          'COLUMN_NAME' => 'user_id',
          'ORDINAL_POSITION' => 1,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'filter_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'user_filter_setting',
          'COLUMN_NAME' => 'filter_id',
          'ORDINAL_POSITION' => 2,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 100,
          'CHARACTER_OCTET_LENGTH' => 100,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'latin1',
          'COLLATION_NAME' => 'latin1_swedish_ci',
          'COLUMN_TYPE' => 'varchar(100)',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'module' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'user_filter_setting',
          'COLUMN_NAME' => 'module',
          'ORDINAL_POSITION' => 3,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 100,
          'CHARACTER_OCTET_LENGTH' => 400,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_general_ci',
          'COLUMN_TYPE' => 'varchar(100)',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
      ),
      'indexes' => 
      array (
        'PRIMARY' => 
        array (
          1 => 
          array (
            'Table' => 'user_filter_setting',
            'Non_unique' => 0,
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => 1,
            'Column_name' => 'user_id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
          2 => 
          array (
            'Table' => 'user_filter_setting',
            'Non_unique' => 0,
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => 2,
            'Column_name' => 'filter_id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
          3 => 
          array (
            'Table' => 'user_filter_setting',
            'Non_unique' => 0,
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => 3,
            'Column_name' => 'module',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => NULL,
    ),
    'user_role' => 
    array (
      'table' => 
      array (
        'table_name' => 'user_role',
        'engine' => 'InnoDB',
        'table_comment' => '',
        'table_collation' => 'utf8mb4_general_ci',
        'character_set_name' => 'utf8mb4',
        'row_format' => 'Dynamic',
      ),
      'columns' => 
      array (
        'id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'user_role',
          'COLUMN_NAME' => 'id',
          'ORDINAL_POSITION' => 1,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => 'auto_increment',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'name' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'user_role',
          'COLUMN_NAME' => 'name',
          'ORDINAL_POSITION' => 2,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 30,
          'CHARACTER_OCTET_LENGTH' => 120,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_general_ci',
          'COLUMN_TYPE' => 'varchar(30)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'hierarchy' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'user_role',
          'COLUMN_NAME' => 'hierarchy',
          'ORDINAL_POSITION' => 3,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
      ),
      'indexes' => 
      array (
        'PRIMARY' => 
        array (
          1 => 
          array (
            'Table' => 'user_role',
            'Non_unique' => 0,
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => 1,
            'Column_name' => 'id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => NULL,
    ),
    'client' => 
    array (
      'table' => 
      array (
        'table_name' => 'client',
        'engine' => 'InnoDB',
        'table_comment' => 'Advisors help and consult clients',
        'table_collation' => 'utf8mb4_unicode_ci',
        'character_set_name' => 'utf8mb4',
        'row_format' => 'Dynamic',
      ),
      'columns' => 
      array (
        'id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'client',
          'COLUMN_NAME' => 'id',
          'ORDINAL_POSITION' => 1,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => 'auto_increment',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'first_name' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'client',
          'COLUMN_NAME' => 'first_name',
          'ORDINAL_POSITION' => 2,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 100,
          'CHARACTER_OCTET_LENGTH' => 400,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_unicode_ci',
          'COLUMN_TYPE' => 'varchar(100)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'last_name' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'client',
          'COLUMN_NAME' => 'last_name',
          'ORDINAL_POSITION' => 3,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 100,
          'CHARACTER_OCTET_LENGTH' => 400,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_unicode_ci',
          'COLUMN_TYPE' => 'varchar(100)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'birthdate' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'client',
          'COLUMN_NAME' => 'birthdate',
          'ORDINAL_POSITION' => 4,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'date',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'date',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'location' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'client',
          'COLUMN_NAME' => 'location',
          'ORDINAL_POSITION' => 5,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 100,
          'CHARACTER_OCTET_LENGTH' => 400,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_unicode_ci',
          'COLUMN_TYPE' => 'varchar(100)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'phone' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'client',
          'COLUMN_NAME' => 'phone',
          'ORDINAL_POSITION' => 6,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 20,
          'CHARACTER_OCTET_LENGTH' => 80,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_unicode_ci',
          'COLUMN_TYPE' => 'varchar(20)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'email' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'client',
          'COLUMN_NAME' => 'email',
          'ORDINAL_POSITION' => 7,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 254,
          'CHARACTER_OCTET_LENGTH' => 1016,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_unicode_ci',
          'COLUMN_TYPE' => 'varchar(254)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'sex' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'client',
          'COLUMN_NAME' => 'sex',
          'ORDINAL_POSITION' => 8,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'enum',
          'CHARACTER_MAXIMUM_LENGTH' => 1,
          'CHARACTER_OCTET_LENGTH' => 4,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_unicode_ci',
          'COLUMN_TYPE' => 'enum(\'M\',\'F\',\'O\')',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'client_message' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'client',
          'COLUMN_NAME' => 'client_message',
          'ORDINAL_POSITION' => 9,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 1000,
          'CHARACTER_OCTET_LENGTH' => 4000,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_unicode_ci',
          'COLUMN_TYPE' => 'varchar(1000)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Message that client submitted via webform',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'vigilance_level' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'client',
          'COLUMN_NAME' => 'vigilance_level',
          'ORDINAL_POSITION' => 10,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'enum',
          'CHARACTER_MAXIMUM_LENGTH' => 6,
          'CHARACTER_OCTET_LENGTH' => 24,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_unicode_ci',
          'COLUMN_TYPE' => 'enum(\'low\',\'medium\',\'high\')',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'user_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'client',
          'COLUMN_NAME' => 'user_id',
          'ORDINAL_POSITION' => 11,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => 'MUL',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'client_status_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'client',
          'COLUMN_NAME' => 'client_status_id',
          'ORDINAL_POSITION' => 12,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => 'MUL',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'assigned_at' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'client',
          'COLUMN_NAME' => 'assigned_at',
          'ORDINAL_POSITION' => 13,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'datetime',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => 0,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'datetime',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'date at which user_id was set',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'updated_at' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'client',
          'COLUMN_NAME' => 'updated_at',
          'ORDINAL_POSITION' => 14,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'datetime',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => 0,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'datetime',
          'COLUMN_KEY' => '',
          'EXTRA' => 'on update current_timestamp()',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'created_at' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'client',
          'COLUMN_NAME' => 'created_at',
          'ORDINAL_POSITION' => 15,
          'COLUMN_DEFAULT' => 'current_timestamp()',
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'datetime',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => 0,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'datetime',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'deleted_at' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'client',
          'COLUMN_NAME' => 'deleted_at',
          'ORDINAL_POSITION' => 16,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'datetime',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => 0,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'datetime',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
      ),
      'indexes' => 
      array (
        'PRIMARY' => 
        array (
          1 => 
          array (
            'Table' => 'client',
            'Non_unique' => 0,
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => 1,
            'Column_name' => 'id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'FK_client_user' => 
        array (
          1 => 
          array (
            'Table' => 'client',
            'Non_unique' => 1,
            'Key_name' => 'FK_client_user',
            'Seq_in_index' => 1,
            'Column_name' => 'user_id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => 'YES',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'FK_client_status' => 
        array (
          1 => 
          array (
            'Table' => 'client',
            'Non_unique' => 1,
            'Key_name' => 'FK_client_status',
            'Seq_in_index' => 1,
            'Column_name' => 'client_status_id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => 'YES',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => NULL,
    ),
    'client_status' => 
    array (
      'table' => 
      array (
        'table_name' => 'client_status',
        'engine' => 'InnoDB',
        'table_comment' => 'Client status',
        'table_collation' => 'utf8mb4_unicode_ci',
        'character_set_name' => 'utf8mb4',
        'row_format' => 'Dynamic',
      ),
      'columns' => 
      array (
        'id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'client_status',
          'COLUMN_NAME' => 'id',
          'ORDINAL_POSITION' => 1,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => 'auto_increment',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'name' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'client_status',
          'COLUMN_NAME' => 'name',
          'ORDINAL_POSITION' => 2,
          'COLUMN_DEFAULT' => '\'0\'',
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 50,
          'CHARACTER_OCTET_LENGTH' => 200,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_unicode_ci',
          'COLUMN_TYPE' => 'varchar(50)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'deleted_at' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'client_status',
          'COLUMN_NAME' => 'deleted_at',
          'ORDINAL_POSITION' => 3,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
      ),
      'indexes' => 
      array (
        'PRIMARY' => 
        array (
          1 => 
          array (
            'Table' => 'client_status',
            'Non_unique' => 0,
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => 1,
            'Column_name' => 'id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => NULL,
    ),
    'phinx_migration_log' => 
    array (
      'table' => 
      array (
        'table_name' => 'phinx_migration_log',
        'engine' => 'InnoDB',
        'table_comment' => '',
        'table_collation' => 'utf8mb4_unicode_ci',
        'character_set_name' => 'utf8mb4',
        'row_format' => 'Dynamic',
      ),
      'columns' => 
      array (
        'version' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'phinx_migration_log',
          'COLUMN_NAME' => 'version',
          'ORDINAL_POSITION' => 1,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'bigint',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 19,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'bigint(20)',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'migration_name' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'phinx_migration_log',
          'COLUMN_NAME' => 'migration_name',
          'ORDINAL_POSITION' => 2,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 100,
          'CHARACTER_OCTET_LENGTH' => 400,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_unicode_ci',
          'COLUMN_TYPE' => 'varchar(100)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'start_time' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'phinx_migration_log',
          'COLUMN_NAME' => 'start_time',
          'ORDINAL_POSITION' => 3,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'timestamp',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => 0,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'timestamp',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'end_time' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'phinx_migration_log',
          'COLUMN_NAME' => 'end_time',
          'ORDINAL_POSITION' => 4,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'timestamp',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => 0,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'timestamp',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'breakpoint' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'phinx_migration_log',
          'COLUMN_NAME' => 'breakpoint',
          'ORDINAL_POSITION' => 5,
          'COLUMN_DEFAULT' => '0',
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'tinyint',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 3,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'tinyint(1)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
      ),
      'indexes' => 
      array (
        'PRIMARY' => 
        array (
          1 => 
          array (
            'Table' => 'phinx_migration_log',
            'Non_unique' => 0,
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => 1,
            'Column_name' => 'version',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => NULL,
    ),
    'user' => 
    array (
      'table' => 
      array (
        'table_name' => 'user',
        'engine' => 'InnoDB',
        'table_comment' => '',
        'table_collation' => 'utf8mb4_unicode_ci',
        'character_set_name' => 'utf8mb4',
        'row_format' => 'Dynamic',
      ),
      'columns' => 
      array (
        'id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'user',
          'COLUMN_NAME' => 'id',
          'ORDINAL_POSITION' => 1,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => 'auto_increment',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'first_name' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'user',
          'COLUMN_NAME' => 'first_name',
          'ORDINAL_POSITION' => 2,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 100,
          'CHARACTER_OCTET_LENGTH' => 400,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_unicode_ci',
          'COLUMN_TYPE' => 'varchar(100)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'last_name' =>
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'user',
          'COLUMN_NAME' => 'last_name',
          'ORDINAL_POSITION' => 3,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 100,
          'CHARACTER_OCTET_LENGTH' => 400,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_unicode_ci',
          'COLUMN_TYPE' => 'varchar(100)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'user_role_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'user',
          'COLUMN_NAME' => 'user_role_id',
          'ORDINAL_POSITION' => 4,
          'COLUMN_DEFAULT' => '0',
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => 'MUL',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'status' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'user',
          'COLUMN_NAME' => 'status',
          'ORDINAL_POSITION' => 5,
          'COLUMN_DEFAULT' => '\'unverified\'',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'enum',
          'CHARACTER_MAXIMUM_LENGTH' => 10,
          'CHARACTER_OCTET_LENGTH' => 40,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_unicode_ci',
          'COLUMN_TYPE' => 'enum(\'active\',\'locked\',\'unverified\',\'suspended\')',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'email' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'user',
          'COLUMN_NAME' => 'email',
          'ORDINAL_POSITION' => 6,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 254,
          'CHARACTER_OCTET_LENGTH' => 1016,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_unicode_ci',
          'COLUMN_TYPE' => 'varchar(254)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'password_hash' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'user',
          'COLUMN_NAME' => 'password_hash',
          'ORDINAL_POSITION' => 7,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 300,
          'CHARACTER_OCTET_LENGTH' => 1200,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_unicode_ci',
          'COLUMN_TYPE' => 'varchar(300)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'theme' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'user',
          'COLUMN_NAME' => 'theme',
          'ORDINAL_POSITION' => 8,
          'COLUMN_DEFAULT' => '\'light\'',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'enum',
          'CHARACTER_MAXIMUM_LENGTH' => 5,
          'CHARACTER_OCTET_LENGTH' => 20,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_unicode_ci',
          'COLUMN_TYPE' => 'enum(\'light\',\'dark\')',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'language' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'user',
          'COLUMN_NAME' => 'language',
          'ORDINAL_POSITION' => 9,
          'COLUMN_DEFAULT' => '\'en_US\'',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'enum',
          'CHARACTER_MAXIMUM_LENGTH' => 5,
          'CHARACTER_OCTET_LENGTH' => 20,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_unicode_ci',
          'COLUMN_TYPE' => 'enum(\'en_US\',\'de_CH\',\'fr_CH\')',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'updated_at' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'user',
          'COLUMN_NAME' => 'updated_at',
          'ORDINAL_POSITION' => 10,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'datetime',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => 0,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'datetime',
          'COLUMN_KEY' => '',
          'EXTRA' => 'on update current_timestamp()',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'created_at' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'user',
          'COLUMN_NAME' => 'created_at',
          'ORDINAL_POSITION' => 11,
          'COLUMN_DEFAULT' => 'current_timestamp()',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'datetime',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => 0,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'datetime',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'deleted_at' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'user',
          'COLUMN_NAME' => 'deleted_at',
          'ORDINAL_POSITION' => 12,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'datetime',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => 0,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'datetime',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
      ),
      'indexes' => 
      array (
        'PRIMARY' => 
        array (
          1 => 
          array (
            'Table' => 'user',
            'Non_unique' => 0,
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => 1,
            'Column_name' => 'id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'FK_user_user_role' => 
        array (
          1 => 
          array (
            'Table' => 'user',
            'Non_unique' => 1,
            'Key_name' => 'FK_user_user_role',
            'Seq_in_index' => 1,
            'Column_name' => 'user_role_id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => NULL,
    ),
    'user_activity' => 
    array (
      'table' => 
      array (
        'table_name' => 'user_activity',
        'engine' => 'InnoDB',
        'table_comment' => '',
        'table_collation' => 'utf8mb4_unicode_ci',
        'character_set_name' => 'utf8mb4',
        'row_format' => 'Dynamic',
      ),
      'columns' => 
      array (
        'id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'user_activity',
          'COLUMN_NAME' => 'id',
          'ORDINAL_POSITION' => 1,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => 'auto_increment',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'user_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'user_activity',
          'COLUMN_NAME' => 'user_id',
          'ORDINAL_POSITION' => 2,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => 'MUL',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'action' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'user_activity',
          'COLUMN_NAME' => 'action',
          'ORDINAL_POSITION' => 3,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'enum',
          'CHARACTER_MAXIMUM_LENGTH' => 7,
          'CHARACTER_OCTET_LENGTH' => 28,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_unicode_ci',
          'COLUMN_TYPE' => 'enum(\'created\',\'updated\',\'deleted\',\'read\')',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'table' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'user_activity',
          'COLUMN_NAME' => 'table',
          'ORDINAL_POSITION' => 4,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 100,
          'CHARACTER_OCTET_LENGTH' => 400,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_unicode_ci',
          'COLUMN_TYPE' => 'varchar(100)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'row_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'user_activity',
          'COLUMN_NAME' => 'row_id',
          'ORDINAL_POSITION' => 5,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'data' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'user_activity',
          'COLUMN_NAME' => 'data',
          'ORDINAL_POSITION' => 6,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'text',
          'CHARACTER_MAXIMUM_LENGTH' => 65535,
          'CHARACTER_OCTET_LENGTH' => 65535,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_unicode_ci',
          'COLUMN_TYPE' => 'text',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'datetime' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'user_activity',
          'COLUMN_NAME' => 'datetime',
          'ORDINAL_POSITION' => 7,
          'COLUMN_DEFAULT' => 'current_timestamp()',
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'datetime',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => 0,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'datetime',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'ip_address' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'user_activity',
          'COLUMN_NAME' => 'ip_address',
          'ORDINAL_POSITION' => 8,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 50,
          'CHARACTER_OCTET_LENGTH' => 200,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_unicode_ci',
          'COLUMN_TYPE' => 'varchar(50)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'user_agent' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'user_activity',
          'COLUMN_NAME' => 'user_agent',
          'ORDINAL_POSITION' => 9,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 255,
          'CHARACTER_OCTET_LENGTH' => 1020,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_unicode_ci',
          'COLUMN_TYPE' => 'varchar(255)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
      ),
      'indexes' => 
      array (
        'PRIMARY' => 
        array (
          1 => 
          array (
            'Table' => 'user_activity',
            'Non_unique' => 0,
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => 1,
            'Column_name' => 'id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'user_activity_user_id_fk' => 
        array (
          1 => 
          array (
            'Table' => 'user_activity',
            'Non_unique' => 1,
            'Key_name' => 'user_activity_user_id_fk',
            'Seq_in_index' => 1,
            'Column_name' => 'user_id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => 'YES',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => NULL,
    ),
    'user_verification' => 
    array (
      'table' => 
      array (
        'table_name' => 'user_verification',
        'engine' => 'InnoDB',
        'table_comment' => '',
        'table_collation' => 'utf8mb4_unicode_ci',
        'character_set_name' => 'utf8mb4',
        'row_format' => 'Dynamic',
      ),
      'columns' => 
      array (
        'id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'user_verification',
          'COLUMN_NAME' => 'id',
          'ORDINAL_POSITION' => 1,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => 'auto_increment',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'user_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'user_verification',
          'COLUMN_NAME' => 'user_id',
          'ORDINAL_POSITION' => 2,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => 'MUL',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'token' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'user_verification',
          'COLUMN_NAME' => 'token',
          'ORDINAL_POSITION' => 3,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 300,
          'CHARACTER_OCTET_LENGTH' => 1200,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_unicode_ci',
          'COLUMN_TYPE' => 'varchar(300)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'expires_at' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'user_verification',
          'COLUMN_NAME' => 'expires_at',
          'ORDINAL_POSITION' => 4,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'bigint',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 19,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'bigint(20)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'used_at' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'user_verification',
          'COLUMN_NAME' => 'used_at',
          'ORDINAL_POSITION' => 5,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'datetime',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => 0,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'datetime',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'created_at' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'user_verification',
          'COLUMN_NAME' => 'created_at',
          'ORDINAL_POSITION' => 6,
          'COLUMN_DEFAULT' => 'current_timestamp()',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'datetime',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => 0,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'datetime',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'deleted_at' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'user_verification',
          'COLUMN_NAME' => 'deleted_at',
          'ORDINAL_POSITION' => 7,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'datetime',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => 0,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'datetime',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
      ),
      'indexes' => 
      array (
        'PRIMARY' => 
        array (
          1 => 
          array (
            'Table' => 'user_verification',
            'Non_unique' => 0,
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => 1,
            'Column_name' => 'id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'FK__user_table' => 
        array (
          1 => 
          array (
            'Table' => 'user_verification',
            'Non_unique' => 1,
            'Key_name' => 'FK__user_table',
            'Seq_in_index' => 1,
            'Column_name' => 'user_id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => NULL,
    ),
  ),
);